all:

m1:
	python3 m1.py --training_x ./resources/MNISTXtrain1.npy --training_y ./resources/MNISTytrain1.npy --outModelFile ./output/m1.h5
m2:
	python3 m2.py --training_x ./resources/MNISTXtrain1.npy --training_y ./resources/MNISTytrain1.npy --outModelFile ./output/m2.h5
m3:
	python3 m3.py --training_x ./resources/MNISTXtrain1.npy --training_y ./resources/MNISTytrain1.npy --outModelFile ./output/m3.h5
m4:
	python3 m4.py --training_x ./resources/MNISTXtrain1.npy --training_y ./resources/MNISTytrain1.npy --outModelFile ./output/m4.h5
test:
